openapi: 3.0.1
info:
  title: aergia API
  description: >
    Aergia, the Greek mythological personification of sloth.<br>
    <br>
    Backend to the sloth gui.<br>
  version: 1.0.0
servers:
  - url: 'https://api.inlitum.dev'

components:
  securitySchemes:
    Bearer Auth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    EmailProperty:
      properties:
        email:
          type: string
          example: john@doe.com
          readOnly: false
    PasswordProperty:
      properties:
        password:
          type: string
          example: johndoe
          readOnly: false
    UsernameProperty:
      properties:
        username:
          type: string
          example: doejohn
          readOnly: false

    LoginRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/EmailProperty'
        - $ref: '#/components/schemas/PasswordProperty'
    RegisterRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/EmailProperty'
        - $ref: '#/components/schemas/PasswordProperty'
        - $ref: '#/components/schemas/UsernameProperty'

paths:
  /login:
    post:
      summary: Logins in
      tags:
        - Auth
      description: >
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    example: bearer
                    default: bearer
                  token:
                    type: string
  /register:
    post:
      summary: Registers a new user
      tags:
        - Auth
      description: >
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    example: bearer
                    default: bearer
                  token:
                    type: string

  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      responses:
        '200':
          description: OK
